### ISSUE TITLE
additional setting to turn off colorization

### ISSUE THREAD

**Issue by tobsn** [TylerBrock/mongo-hacker#114]
add another settings flag to turn colors on/off
reason: some shells have problems with the colors. right now we're using MongoChef and it doesn't support shell colors - had to remove the isWindow() to make a color on/off switch out of force colors. would be nice to have a default _off_

**Comment by stennie** [comment]
You can force colours off by adding `__colorize = false;` at the end of your `.mongorc.js`.

For Robomongo I set this in `~/.robomongorc.js` so I still have colour in my normal `mongo` shell.

**Comment by akostadinov** [comment]
+1, add option to disable colors. In addition - detect tty and enable colors only in ttys. Otherwise scripting mongo queries is a pain.

**Comment by TylerBrock** [comment]
Sounds good, in the meantime you can run mongo scripts without the color by invoking the shell with `--norc` so that mongo-hacker doesn't interfere.
