### ISSUE TITLE
Is it possible to further customize mongo-hacker?

### ISSUE THREAD

**Issue by devinus** [TylerBrock/mongo-hacker#116]
E.g. a `.mongo_hackerrc.js`

**Comment by TylerBrock** [comment]
Hey @devinus. Sure.

If you make a .mongorc.js a directory in your home folder as opposed to a file then the contents of it will be executed in alphabetical order. One of them could be mongo_hacker and depending on whether you want the additional JS code to execute before/after mongo hacker you can name the file appropriately.
