### ISSUE TITLE
sh.status in 3.0 now includes balancer state

### ISSUE THREAD

**Issue by gianpaj** [TylerBrock/mongo-hacker#122]
https://jira.mongodb.org/browse/SERVER-14882
https://github.com/mongodb/mongo/blob/v3.0/src/mongo/shell/shardingtest.js#L655
http://docs.mongodb.org/manual/reference/method/sh.status/#balancer

**Comment by TylerBrock** [comment]
Want to make a pull request?

**Comment by gianpaj** [comment]
Sure can.

![4__gianfranco_gianpaj____github_tylerbrock_mongo-hacker__zsh_](https://cloud.githubusercontent.com/assets/899175/6772285/f2a96d3e-d0f1-11e4-8fbb-3dc1f886447f.png)

**Comment by TylerBrock** [comment]
That looks hot! Nice work sir.
