### ISSUE TITLE
Colorization not working

### ISSUE THREAD

**Issue by rubenvereecken** [TylerBrock/mongo-hacker#125]
It's been a while since I've used my trust Mongo shell but apparently since the last time something broke and I don't get a colorized shell anymore. Here's some relevant version info, as printed by the Mongo shell.

    MongoDB shell version: 2.4.9
    Mongo-Hacker 0.0.5

I scanned through the `mongorc.js` file and even turned `force_color` on. Nothing though. What could I be doing wrong?

**Comment by TylerBrock** [comment]
Can you try using a newer version of the shell? 2.4.x is quite old although I'm surprised it doesn't work. In the meantime I can investigate why it doesn't work with 2.4.x

**Comment by stennie** [comment]
@rubenvereecken What O/S are you using? Are you seeing escape characters instead of color, or just no difference when mongo-hacker is loaded?

**Comment by rubenvereecken** [comment]
Sorry for the late reply!

I'm running Linux Mint 17 Cinnamon. I don't think I updated since the last time it worked which is about half a year ago.

Will report back once I updated Mongo.

**Comment by rubenvereecken** [comment]
I updated to Mongo 3.0.1 manually and behold, colors work again! I never touched the `.mongorc.js` file (in fact I made sure it didn't change) but there they are... pretty colors.

I'll leave this open for you to close if you don't feel it necessary to investigate further. As I said, it even worked before so I'm really at a loss to say what caused it.

**Comment by TylerBrock** [comment]
Hrm... ok, thank you. We will re-open if we get more reports of this being an issue with older shells. Although it should be working.
