### ISSUE TITLE
"edit" command polluted with ASCII color codes

### ISSUE THREAD

**Issue by jelder** [TylerBrock/mongo-hacker#13]
`obj = db.mycollection.find().pretty()`
`edit obj`

```
{
  ^[[33m"_mongo"^[[m: connection to 127.0.0.1,
  ^[[33m"_db"^[[m: ObjectId(^[[32;4m"blah.str"^[[m),
  ^[[33m"_collection"^[[m: ObjectId(^[[32;4m"blah.mycollection.str"^[[m),
  ^[[33m"_ns"^[[m: ^[[32;1m"blah.mycollection"^[[m,
  ^[[33m"_query"^[[m: {
```

**Comment by candland** [comment]
+1 would love to be able to use edit

**Comment by TylerBrock** [comment]
Sorry about this. I'd like to take a look at this but don't have the time at the moment.

I would, of course, be willing to accept a pull request if you wanted to take a stab at it.

**Comment by stennie** [comment]
Ooh! Forgot about this as I've been happily using on my local. I'll rebase and make a PR :)

**Comment by TylerBrock** [comment]
You've got a patch @stennie?! Hooray!
