### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by YoniAmir** [TylerBrock/mongo-hacker#130]
Hi, i'm not sure the method I used to install mongo-hacker at the time but I'm trying to uninstall completely.

Please advise. 

Thanks.

**Comment by TylerBrock** [comment]
To uninstall you can remove .mongorc.js from the home directory of the current user: `rm ~/.mongorc.js`

To uninstall completely would depend on how it was installed.

- If via NPM: `npm remove mongo-hacker`
- If via Manually: remove the directory it was cloned into

Alternatively, you can run the shell with the `norc` flag to disable it for a single session: `mongo --norc`

Let me know if that works for you.

**Comment by YoniAmir** [comment]
Seems to do the trick. Thanks a lot.

**Comment by gianpaj** [comment]
As a side note, if you'd like to disable mongo-hacker or the any other `.mongorc.js` you can run the mongo shell as follows:
```
mongo --norc
```

**Comment by TylerBrock** [comment]
@gianpaj dude... i mention that in my comment explicitly. Step your game up player.
