### ISSUE TITLE
Bump minimum MongoDB version to 2.4

### ISSUE THREAD

**Issue by stennie** [TylerBrock/mongo-hacker#131]
The changes merged in PR#129 use Array functions which require [MongoDB 2.4+](http://docs.mongodb.org/manual/release-notes/2.4-javascript/#modernized-javascript-implementation-es5).

I think it makes sense to bump the minimum version to 2.4, since 2.4+ uses the V8 JavaScript engine while MongoDB 2.2 (current minimum version) uses SpiderMonkey.

**Comment by pvdb** [comment]
@stennie - thanks for pointing that out, I will definitely keep Mongo version dependencies in mind for subsequent pull requests! :thumbsup:
