### ISSUE TITLE
remove setIndexParanoia from README.md file

### ISSUE THREAD

**Issue by rodfersou** [TylerBrock/mongo-hacker#137]
I couldn't find any reference of setIndexParanoia into mongo-hacker code, so I suppose it was about old version of the code

**Comment by rodfersou** [comment]
Is there another way to show index information?

**Comment by TylerBrock** [comment]
You can use `cursor.explain()` but mongo-hacker itself no longer provides
that functionality:

http://docs.mongodb.org/manual/reference/method/cursor.explain/

**Comment by rodfersou** [comment]
@TylerBrock thank you for the explanation

**Comment by TylerBrock** [comment]
No problem, good luck!
