### ISSUE TITLE
'make' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by wzup** [TylerBrock/mongo-hacker#138]
Cannot install on Win 8.1 x64. Get this error:

```
'make' is not recognized as an internal or external command,
operable program or batch file.
```

How to solve it? Without installing Cygwin

**Comment by TylerBrock** [comment]
Sorry, it doesn't really work without `make`. Maybe I should re-write it to use node for concatenating the files together. If you want to take a stab at it i'd accept the pull request.

**Comment by TylerBrock** [comment]
Perhaps there is a node tool out there that already does this but I think it's fairly trivial.

**Comment by feimosi** [comment]
The same problem here, Windows 10, node v.5.5.0.
After providing `make` from GnuWin32 I ended up with the following error:
```
helpers.js hacks/index_paranoia.js hacks/old_aggregation.js hacks/prompt.js hacks/sh_status.js hacks/show.js hacks/uuid.js hacks/verbose.js > mongo_hacker.js
      0 [main] sh 9328 C:\Program Files\Git\usr\bin\sh.exe: *** fatal error in forked process - fork: can't reserve memory for parent stack 0x600000 - 0x800000, (child has 0x400000 - 0x600000), Win32 error 487
    466 [main] sh 9328 cygwin_exception::open_stackdumpfile: Dumping stack trace to sh.exe.stackdump
      1 [main] sh 7800 fork: child -1 - forked process 9328 died unexpectedly, retry 0, exit code 0x100, errno 11
/usr/bin/sh: fork: retry: No child processes
```

**Comment by gianpaj** [comment]
Could this possibly help?
https://github.com/shelljs/shelljs#make-tool (Portable Unix shell commands for Node.js)
A convenience script shelljs/make is also provided to mimic the behavior of a Unix Makefile

**Comment by TylerBrock** [comment]
I need to remove make from the equation and just use node to cat the files
together.

**Comment by gaurav51289** [comment]
Any solution for installing it on windows? 
Error : `'make' is not recognized as an internal or external command,
operable program or batch file.`

**Comment by spflow** [comment]
-Download 'Make for Windows' @ http://gnuwin32.sourceforge.net/packages/make.htm
-Add the make.exe directory to your PATH variable

**Comment by TylerBrock** [comment]
Ugh I'm sorry, I REALLY need to do this just in pure node.

**Comment by cassianomon** [comment]
Installed 'make-3.81.exe" as @spflow said but still having the error 
> 'make' is not recognized as an internal or external command, operable program or batch file.


I am on Windows 10, node v.4.4.4, npm 2.15.1

**Comment by jg-digital-media** [comment]
Any update on a timetable for this? Thanks  :)

**Comment by Wo1v3r** [comment]
Any alternative meanwhile except for downloading make for windows? :x

**Comment by cassianomon** [comment]
Actually I did made it work but can't remember how :/

**Comment by ashishTheCoder** [comment]
I faced the same problem.So to install it properly I installed  **http://gnuwin32.sourceforge.net/packages/make.htm** in my system and set path variable but after that I start getting **cat is not recognized** error . 

So than I used` gitbash` for installation and it works for me.

**Comment by Secular12** [comment]
@TylerBrock Any updates on this?

**Comment by stennie** [comment]
By default Windows doesn't include the `make` command used to build Mongo Hacker. 

On Windows It will likely be more straightforward to download `make` and install Mongo Hacker from GitHub (instead of via NPM).

**Comment by Hspharwinder** [comment]
Visit here https://sourceforge.net/projects/mingw/
download MinGW - Minimalist GNU for Windows and install it.
Set system variable path 
C:\MinGW\bin

For help check video youtube.com/watch?v=sXW2VLrQ3Bs

**Comment by WinterOfMaple2016** [comment]
> -Download 'Make for Windows' @ http://gnuwin32.sourceforge.net/packages/make.htm -Add the make.exe directory to your PATH variable
> 
> It worked for me, not sure why @feimosi had problems.
Set system variable path 
C:\Program Files (x86)\GnuWin32\bin

**Comment by hassy97** [comment]
make : The term 'make' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At line:1 char:1
+ make deps
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (make:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by stennie** [comment]
@hassy97 I recommend using the new MongoDB Shell (`mongosh`) instead of Mongo Hacker and the legacy `mongo` shell: https://www.mongodb.com/docs/mongodb-shell/,

`mongosh` is built on top of the Node.js REPL and has more modern features including syntax highlighting, autocomplete, and support for `npm` packages: https://www.mongodb.com/blog/post/introducing-the-new-shell.

`mongosh` is also embedded into GUI tools like [MongoDB Compass](https://www.mongodb.com/docs/compass/current/embedded-shell/) and [Jetbrains DataGrip](https://blog.jetbrains.com/datagrip/2020/06/16/introducing-mongodb-shell-in-datagrip/).

The legacy `mongo` shell has been fully deprecated by `mongosh` as of the MongoDB 6.0 release.
