### ISSUE TITLE
Invalid flags supplied to RegExp constructor

### ISSUE THREAD

**Issue by msjaiswal** [TylerBrock/mongo-hacker#158]
I ran this from a python script: 

`sink.find({ "url": { "$regex": re.compile("^\?.*")}}):`

Script ran just fine but when I try to run `db.currentOp()`, it gives the following error:
`2016-03-28T11:35:09.902+0000 Error: 16863 Error converting //^\?.*//u in field $regex to a JS RegExp object: SyntaxError: Invalid flags supplied to RegExp constructor 'u' at /root/.mongorc.js:341
`
Here is some code snippet from mongorc.js

```
    // push one level of indent
    indent += tabSpace;

    var total = 0;
    for ( var k in x ) total++;    // <---- Line no. 341 
    if ( total === 0 ) {
        s += indent + lineEnding;
    }
```

**Comment by TylerBrock** [comment]
Hey @msjaiswal thanks for reporing this. That is an odd one, are you sure the code is related to the error? There doesn't seem to be any regex related things going on in that section of the mongorc from what I can tell.

**Comment by stennie** [comment]
Closing old issue as I'm not sure how to repro this.

It looks like the original approach may be invoking the `mongo` shell via Python. If so, I'd recommend calling MongoDB commands directly from Python.
