### ISSUE TITLE
TypeError: result.queryPlanner is undefined

### ISSUE THREAD

**Issue by jsherard** [TylerBrock/mongo-hacker#159]
i get the following error when running a query using mongohacker:

```
JSHERARD-12282m(mongod-3.2.3) test> db.foo.find({_id:0})
{
  "_id": 0,
  "x": 0
}
TypeError: result.queryPlanner is undefined
```

**Comment by TylerBrock** [comment]
Hey @jsherard thanks for reporting the problem, I'm sorry you are having trouble. Can you give me more info about the version of mongodb you are running?

**Comment by jsherard** [comment]
mongod-3.2.3

**Comment by stennie** [comment]
Closing old issue. I can't reproduce this in a modern version of MongoDB (3.4+).
