### ISSUE TITLE
TypeError: this._db._initExtraInfo is not a function

### ISSUE THREAD

**Issue by 4Z4T4R** [TylerBrock/mongo-hacker#161]
Originally thought to be an issue with MongoDB Shell.  They claim it is a result of Mongo-Hacker.  Here's the original ticket at MongoDB with a complete repro procedure.

https://jira.mongodb.org/browse/SERVER-24065

**Comment by TylerBrock** [comment]
Hey, thanks for reporting this. What version of the shell are you running?

**Comment by toszter** [comment]
0.0.13 -- Apologies for failing to mention. :)

**Comment by TylerBrock** [comment]
no thats ok, i meant what version of the MongoDB shell are you running?

**Comment by toszter** [comment]
v3.2.6 she'll into a v3.2.5 remote server--- details are in the Mongo JIRA. :)

**Comment by chintan100** [comment]
I get this error as well. Below is my configuration: 

```
MongoDB shell version v3.6.5
MongoDB server version: 3.2.19
Mongo-Hacker 0.0.14
```

I am trying to delete earliest 10 records from mongoDB using this query: 

```
db.getCollection('Status').find({}).sort({_created_at:1}).limit(10).remove()
2018-12-25T18:04:27.739+0530 E QUERY    [thread1] TypeError: this._db._initExtraInfo is not a function :
DBQuery.prototype.remove@/Users/xxxxxxxxxx/.mongorc.js:448:5
@(shell):1:1
```

However, if I just do `db.getCollection('Status').find({}).sort({_created_at:1}).limit(10)` it works fine and does list the records. If I add `.remove()`, it gives the above error.
