### ISSUE TITLE
installation under win10 fails

### ISSUE THREAD

**Issue by duyanning** [TylerBrock/mongo-hacker#165]
npm ERR! Windows_NT 10.0.14393  
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "mong
o-hacker"  
npm ERR! node v5.4.1  
npm ERR! npm  v3.3.12  
npm ERR! code ELIFECYCLE                                                                                                                

npm ERR! mongo-hacker@0.0.14 install: `make install`  
npm ERR! Exit status 1  
npm ERR!  
npm ERR! Failed at the mongo-hacker@0.0.14 install script 'make install'.  
npm ERR! Make sure you have the latest version of node.js and npm installed.  
npm ERR! If you do, this is most likely a problem with the mongo-hacker package,  
npm ERR! not with npm itself.  
npm ERR! Tell the author that this fails on your system:  
npm ERR!     make install  
npm ERR! You can get their info via:  
npm ERR!     npm owner ls mongo-hacker  
npm ERR! There is likely additional logging output above.  
npm ERR! Windows_NT 10.0.14393  
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "mong
o-hacker"  
npm ERR! node v5.4.1  
npm ERR! npm  v3.3.12  
npm ERR! path C:\Program Files\MongoDB\Server\3.2\bin\npm-debug.log.824f03705fe616cc893bde538f6f604c  
npm ERR! code EPERM  
npm ERR! errno -4048  
npm ERR! syscall open                                                                                                                   

npm ERR! Error: EPERM: operation not permitted, open 'C:\Program Files\MongoDB\Server\3.2\bin\npm-debug.log.824f03705fe616cc893bde538f6f
604c'  
npm ERR!     at Error (native)  
npm ERR!  { [Error: EPERM: operation not permitted, open 'C:\Program Files\MongoDB\Server\3.2\bin\npm-debug.log.824f03705fe616cc893bde53
8f6f604c']  
npm ERR!   errno: -4048,  
npm ERR!   code: 'EPERM',  
npm ERR!   syscall: 'open',  
npm ERR!   path: 'C:\Program Files\MongoDB\Server\3.2\bin\npm-debug.log.824f03705fe616cc893bde538f6f604c' }  
npm ERR!  
npm ERR! Please try running this command again as root/Administrator.                                                                   

npm ERR! Please include the following file with any support request:  
npm ERR!     C:\Program Files\MongoDB\Server\3.2\bin\npm-debug.log

**Comment by cringer** [comment]
bump...
same here, pretty sad this looks like a nice tool

**Comment by sunitjoshi** [comment]
Ditto...used to work before!

**Comment by glng3r28** [comment]
Same problem on my end here as well

**Comment by bheklilr** [comment]
Just came across this project and would really like to use it, but I'm stuck on windows for work.  Any way this issue could get some movement?  Is there anything I might be able to do to help?

**Comment by stennie** [comment]
By default Windows doesn't include the `make` command used to build Mongo Hacker. See #175 for some suggested options that appear to have worked for others.

On Windows It will likely be more straightforward to download `make` and install Mongo Hacker from GitHub (instead of via NPM).
