### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by zshamrock** [TylerBrock/mongo-hacker#166]
Hi, Tyler. Thank you for the nice work. 

Could you, please, explain how does it work, i.e. how it "injects" hacks into the mongo shell? Does mongo shell have the plugin system, and you just jack-in? Could you, please, share some technical details?

Yes, I know the source code is available, there are lots of javascript files, but how do they integrate with the official mongo shell?

Thank you.

**Comment by TylerBrock** [comment]
When the `mongo` shell starts it:
 - executes a bundle of JS that has been written by the folks at MongoDB
 - executes whatever is in ~/.mongorc

`mongo-hacker` overrides and redefines some of the JavaScript provided by MongoDB during the shell initialization to add and in some cases modify the original functionality.
