### ISSUE TITLE
Issue to install mongo-hacker on MacOs Sierra 10.12.1

### ISSUE THREAD

**Issue by pablodc16** [TylerBrock/mongo-hacker#168]
Hi Tyler,

I was trying to install the mongo-hacker on my computer but I got an error during the process:

sudo npm install -g mongo-hacker
Password:

> mongo-hacker@0.0.15 install /usr/local/lib/node_modules/mongo-hacker
> make install

cat config.js base.js hacks/aggregation.js hacks/api.js hacks/auto_complete.js hacks/cmd_search.js hacks/color.js hacks/common.js hacks/count.js hacks/dbref.js hacks/find_and_modify.js hacks/helpers.js hacks/index_paranoia.js hacks/old_aggregation.js hacks/prompt.js hacks/ps.js hacks/randomise.js hacks/sh_status.js hacks/show.js hacks/uuid.js hacks/verbose.js > mongo_hacker.js
INSTALLATION
Linking MongoHacker to .mongorc.js in your home directory:
mv: rename /Users/pabloduran/.mongorc.js to /Users/pabloduran/.mongorc.js.orig: Permission denied
Backed up ~/.mongorc.js.orig
ln -sf "/usr/local/lib/node_modules/mongo-hacker/mongo_hacker.js" ~/.mongorc.js
ln: /Users/pabloduran/.mongorc.js: Permission denied
make: *** [install] Error 1
npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "mongo-hacker"
npm ERR! node v6.9.1
npm ERR! npm  v4.0.2
npm ERR! code ELIFECYCLE

npm ERR! mongo-hacker@0.0.15 install: `make install`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the mongo-hacker@0.0.15 install script 'make install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mongo-hacker package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     make install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mongo-hacker
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mongo-hacker
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/pabloduran/npm-debug.log

I recently updated my nodejs and npm to the latest version but the issue remains, can you please help me to fix this? There is anything I'm missing in order to install the package?

I'm using  MacOs Sierra 10.12.1

Please let me know if you have any question or if you need more information.

Best regards.

**Comment by pbozzi** [comment]
Hi namefellow,

Same was happening here:
```
pablo:~ pablo$ sudo npm install -g mongo-hacker

> mongo-hacker@0.0.15 install /usr/local/lib/node_modules/mongo-hacker
> make install

cat config.js base.js hacks/aggregation.js hacks/api.js hacks/auto_complete.js hacks/cmd_search.js hacks/color.js hacks/common.js hacks/count.js hacks/dbref.js hacks/find_and_modify.js hacks/helpers.js hacks/index_paranoia.js hacks/old_aggregation.js hacks/prompt.js hacks/ps.js hacks/randomise.js hacks/sh_status.js hacks/show.js hacks/uuid.js hacks/verbose.js > mongo_hacker.js
INSTALLATION
Linking MongoHacker to .mongorc.js in your home directory:
ln -sf "/usr/local/lib/node_modules/mongo-hacker/mongo_hacker.js" ~/.mongorc.js
ln: /Users/pablo/.mongorc.js: Permission denied
make: *** [install] Error 1
npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "mongo-hacker"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! mongo-hacker@0.0.15 install: `make install`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the mongo-hacker@0.0.15 install script 'make install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mongo-hacker package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     make install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mongo-hacker
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mongo-hacker
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/pablo/npm-debug.log
```

Just changed owner of .npm file and node_modules folder, like [here:](http://stackoverflow.com/questions/33725639/npm-install-g-less-does-not-work)
```
sudo chown -R $USER /usr/local/lib/node_modules/
sudo chown -R $USER /usr/lib/node_modules
sudo chown -R $USER ./.npm
```

And worked.
```
pablo:~ pablo$ npm install -g mongo-hacker

> mongo-hacker@0.0.15 install /usr/local/lib/node_modules/mongo-hacker
> make install

cat config.js base.js hacks/aggregation.js hacks/api.js hacks/auto_complete.js hacks/cmd_search.js hacks/color.js hacks/common.js hacks/count.js hacks/dbref.js hacks/find_and_modify.js hacks/helpers.js hacks/index_paranoia.js hacks/old_aggregation.js hacks/prompt.js hacks/ps.js hacks/randomise.js hacks/sh_status.js hacks/show.js hacks/uuid.js hacks/verbose.js > mongo_hacker.js
INSTALLATION
Linking MongoHacker to .mongorc.js in your home directory:
ln -sf "/usr/local/lib/node_modules/mongo-hacker/mongo_hacker.js" ~/.mongorc.js
/usr/local/lib
└── mongo-hacker@0.0.15 
```
