### ISSUE TITLE
how to colorize prompt?

### ISSUE THREAD

**Issue by timotheecour** [TylerBrock/mongo-hacker#171]
@TylerBrock

tried modifying code as follows:
```
var prompt_string = "PROMPT";
return colorize(prompt_string, mongo_hacker_config.colors.date);
```

but it prints escaped code as follows:
[34mPROMPT[m^C

**Comment by timotheecour** [comment]
related:
* https://github.com/antirez/linenoise/pull/135
* https://jira.mongodb.org/browse/SERVER-18065

**Comment by tukusejssirs** [comment]
@TylerBrock, this helped me a lot. Could this be noted somewhere like a FAQ or tutorials or even in the `README.md`?
