### ISSUE TITLE
malformed .mongorc file after installing

### ISSUE THREAD

**Issue by eamonnmcevoy** [TylerBrock/mongo-hacker#173]
Installed in cygwin on windows 10. I get the following error when running `mongo` command:

![image](https://user-images.githubusercontent.com/15125471/27809851-e4ff4f14-6096-11e7-8509-4c5cb4403256.png)

I can open `mongorc.js` in vim but not sublime:
![image](https://user-images.githubusercontent.com/15125471/27809887-4f7a4128-6097-11e7-9e2e-b3c231561fd2.png)

**Comment by TylerBrock** [comment]
Sorry. It doesn't work with windows.


-Tyler

**Comment by taobo33** [comment]
Is there anything I can do to reverse this? I uninstalled mongo-hacker but the issue remains...
