### ISSUE TITLE
'make' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by jankoboz** [TylerBrock/mongo-hacker#175]
> mongo-hacker@0.0.15 install C:\Users\dillt\AppData\Roaming\npm\node_modules\mongo-hacker
> make install

'make' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "mongo-hacker"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

**Comment by JD-V** [comment]
Even I faced this while trying to install using npm install command.

**Comment by TylerBrock** [comment]
Doesn't support windows, sorry.


-Tyler

**Comment by rajkumarsrinivas** [comment]
I have made it work in Windows. Install make in Windows from the below link. 
http://gnuwin32.sourceforge.net/packages/make.htm

And set up the path variable. Then go for npm install.

**Comment by 2bon** [comment]
`setx scoop "C:\Users\%username%\scoop" /M
======run 'cmd' as admin 2 use 'setx'=====
echo %scoop%
setx scoopApps "%scoop%\apps" /M
echo %scoopApps%

scoop install make 
=======Phase 3: Create the makePath environment variable===
setx makePath "%scoopApps%/make" /M
echo %makePath%
setx makeBin "%makePath%/Bin" /M
echo %makeBin%
setx Path "%Path%;%makeBin%" /M
echo %Path%

=======Phase 4: Test and ensure===
`
