### ISSUE TITLE
Add administrator flag in configuration

### ISSUE THREAD

**Issue by Crandel** [TylerBrock/mongo-hacker#180]
Hi,
I try to use mongo hacker with my project, but I`m not an administrator in MongoDB, just a regular user and I got this error message each time I run any query
```
QUERY    [thread1] Error: profile command failed: {
  "ok": 0,
  "errmsg": "not authorized on ibp to execute command { profile: -1.0 }",
  "code": 13
} :
_getErrorWithCode@src/mongo/shell/utils.js:25:13
DB.prototype.getProfilingStatus@src/mongo/shell/db.js:290:1
```

It would be nice if I just change one field in configuration and any helper function will know that profiling is not available.
Thanks

**Comment by stennie** [comment]
This will be resolved via the fix for #195.
