### ISSUE TITLE
not an issue - theme

### ISSUE THREAD

**Issue by larafale** [TylerBrock/mongo-hacker#183]
hello, big fan of mongo hacker. I do get some colors, but I'd like to get the same nice colors/theme of the screenshot terminal ? where can I get that ? thanks

**Comment by TylerBrock** [comment]
Hey, thanks for the support! I think the theme was my own but based heavily on TommorrowNight-Eighties.

It's in my dotfiles here: https://github.com/TylerBrock/dotfiles/blob/master/tomorrow-night-tyler.terminal

You can download that file, open it in Terminal.app and be good to go, save it as your own profile, etc.

**Comment by larafale** [comment]
thx Tyler appreciate :) !
