### ISSUE TITLE
Installation guide is wrong: deletes soft-linked file after creating it

### ISSUE THREAD

**Issue by salty-horse** [TylerBrock/mongo-hacker#185]
The installation guide in the README is:
```
git clone https://github.com/TylerBrock/mongo-hacker
cd mongo-hacker
make install
cd ..
rm -rdf mongo-hacker/
```
`make install` softlinks a file in `mongo-hacker/` to `~/.mongorc.js`.
`rm` then deletes that original file, so the soft link is now broken.

Also, the `-d` flag for `rm` is redundant. It's implied by `-r`.

**Comment by michaelfdias** [comment]
Great report! I sent a PR to fix it #188.

**Comment by salty-horse** [comment]
What about the `-d` flag for `rm` :)

**Comment by michaelfdias** [comment]
It also makes sense and can be improved, but it doesn't throw an error or side effect so far.
