### ISSUE TITLE
Delete word backwards in a query

### ISSUE THREAD

**Issue by dpkshrma** [TylerBrock/mongo-hacker#190]
Is it possible to add a word detection mechanism while deleting using shortcut `ctrl-w` which is present in most shells by default.

For example, pressing `ctrl-w` on the query: `> db.cars.insert` removes the entire query
Expected functionality would be just the removal of `.insert`

I'm not sure if that's a feasible request or not but putting it forward because I think it is very annoying not to be able to quickly delete a word while typing in a query.

**Comment by stennie** [comment]
@dpkshrma [Keyboard shortcuts](https://docs.mongodb.com/manual/reference/mongo-shell/#keyboard-shortcuts) are part of the underlying `mongo` shell and cannot be overridden through JavaScript extensions like Mongo Hacker.

The equivalent of the `ctrl-w` behaviour you described is currently `Meta-[Backspace]` (backward-kill-word).

On macOS the `Meta` key is mapped to `ESC` by default, so `esc` + `delete` should work.
