### ISSUE TITLE
Format code with prettier

### ISSUE THREAD

**Issue by gianpaj** [TylerBrock/mongo-hacker#210]
### Environment

- VScode (Visual Studio Code)

I'm looking to add a feature, but before, and in addition, I'd like to propose to format the JS code with [prettier](https://prettier.io/)

For example:
`.prettierrc`
```json
{
    "tabWidth": 4,
    "useTabs": false,
    "printWidth": 120,
    "singleQuote": true
}

```

More options: https://prettier.io/docs/en/options.html

Happy to open a PR to discuss and determine which settings are the best for this project.

**Comment by stennie** [comment]
HI @gianpaj,

Given the generally low level of commit activity for this project I don't think there's a huge win in reformatting the code. Doing so may make the history harder to compare, which is probably a more important concern than prettiness at this stage.

However, if you want to submit a PR that would be helpful to see how significant the proposed changes would be.

I would also suggest looking at the [new MongoDB Shell](https://www.mongodb.com/blog/post/introducing-the-new-shell) which is written using more modern JavaScript & conventions.

Cheers,
Stennie

**Comment by gianpaj** [comment]
hey @stennie hope you're doing well down-under 🙃 

The new MongoDB shell looks great! I'll take a look at it.

**Comment by TylerBrock** [comment]
Hey @gianpaj yep, I think those settings would be best and agree with @stennie
