### ISSUE TITLE
 Failed at the mongo-hacker@0.0.3 install script.

### ISSUE THREAD

**Issue by danaanclarke** [TylerBrock/mongo-hacker#88]
I'm new to development, so I could be missing something obvious here, but when I try npm install -g mongo-hacker, I get the following: https://www.dropbox.com/s/jvh79bqlidza3r8/Screenshot%202014-06-27%2014.31.05.png

I'm currently in a development bootcamp, and a number of my classmates had the same issue.

**Comment by SherG** [comment]
I had the same problem listed at the start of this thread. Following Tyler's suggestion to run ```brew update && brew upgrade``` worked.  See results: https://www.dropbox.com/s/gx84m2n7urfkda4/homebrewJ.jpg?dl=0

**Comment by jwerre** [comment]
I'm having the same issue ( osx@10.11.2, Node@4.2.4, npm@2.14.12 ). I did not install Node with `brew`

	sudo npm install -g mongo-hacker

	> mongo-hacker@0.0.11 install /usr/local/lib/node_modules/mongo-hacker
	> make install

	cat config.js base.js hacks/aggregation.js hacks/api.js hacks/auto_complete.js hacks/cmd_search.js hacks/color.js hacks/common.js hacks/count.js hacks/find_and_modify.js hacks/helpers.js hacks/index_paranoia.js hacks/old_aggregation.js hacks/prompt.js hacks/sh_status.js hacks/show.js hacks/uuid.js hacks/verbose.js > mongo_hacker.js
	INSTALLATION
	Linking MongoHacker to .mongorc.js in your home directory:
	ln -sf "/usr/local/lib/node_modules/mongo-hacker/mongo_hacker.js" ~/.mongorc.js
	ln: /Users/jw/.mongorc.js: Permission denied
	make: *** [install] Error 1
	npm ERR! Darwin 15.2.0
	npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "mongo-hacker"
	npm ERR! node v4.2.4
	npm ERR! npm  v2.14.12
	npm ERR! code ELIFECYCLE

	npm ERR! mongo-hacker@0.0.11 install: `make install`
	npm ERR! Exit status 2
	npm ERR! 
	npm ERR! Failed at the mongo-hacker@0.0.11 install script 'make install'.
	npm ERR! This is most likely a problem with the mongo-hacker package,
	npm ERR! not with npm itself.
	npm ERR! Tell the author that this fails on your system:
	npm ERR!     make install
	npm ERR! You can get their info via:
	npm ERR!     npm owner ls mongo-hacker
	npm ERR! There is likely additional logging output above.

	> mongo-hacker@0.0.11 postuninstall /usr/local/lib/node_modules/mongo-hacker
	> make uninstall

	rm -f ~/.mongorc.js
	mv ~/.mongorc.js.orig ~/.mongorc.js
	mv: rename /Users/jw/.mongorc.js.orig to /Users/jw/.mongorc.js: No such file or directory
	make: [uninstall] Error 1 (ignored)

	npm ERR! Please include the following file with any support request:
	npm ERR!     /Users/jw/npm-debug.log

**Comment by jwerre** [comment]
This worked for me:

    git clone --depth=1 https://github.com/TylerBrock/mongo-hacker.git
    cd mongo-hacker
    make install

**Comment by TylerBrock** [comment]
@jwerre I would highly recommend installing node with brew or via a node version manager.

**Comment by tylerhartley** [comment]
Also experiencing this problem on Ubuntu 14.04. 

Without sudo I get:

```
> npm install -g mongo-hacker

npm ERR! tar.unpack untar error /home/tyler/.npm/mongo-hacker/0.0.11/package.tgz
npm ERR! Linux 3.16.0-57-generic
npm ERR! argv "node" "/usr/bin/npm" "install" "-g" "mongo-hacker"
npm ERR! node v0.10.37
npm ERR! npm  v2.7.5
npm ERR! path /usr/lib/node_modules/mongo-hacker
npm ERR! code EACCES
npm ERR! errno 3

npm ERR! Error: EACCES, mkdir '/usr/lib/node_modules/mongo-hacker'
npm ERR!  { [Error: EACCES, mkdir '/usr/lib/node_modules/mongo-hacker']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/usr/lib/node_modules/mongo-hacker',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: '/usr/lib/node_modules/mongo-hacker',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack: 
npm ERR!    [ '/usr/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:36:23',
npm ERR!      '/usr/lib/node_modules/npm/node_modules/mkdirp/index.js:46:53',
npm ERR!      'Object.oncomplete (fs.js:108:15)' ] }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/tyler/npm-debug.log
```

So, trying to access `/usr/lib/node_modules`...no surprise that permission was denied. Ok, add sudo: 

```
> sudo npm install -g mongo-hacker

> mongo-hacker@0.0.11 install /usr/lib/node_modules/mongo-hacker
> make install

cat config.js base.js hacks/aggregation.js hacks/api.js hacks/auto_complete.js hacks/cmd_search.js hacks/color.js hacks/common.js hacks/count.js hacks/find_and_modify.js hacks/helpers.js hacks/index_paranoia.js hacks/old_aggregation.js hacks/prompt.js hacks/show.js hacks/sh_status.js hacks/uuid.js hacks/verbose.js > mongo_hacker.js
INSTALLATION
Linking MongoHacker to .mongorc.js in your home directory:
ln -sf "/usr/lib/node_modules/mongo-hacker/mongo_hacker.js" ~/.mongorc.js
ln: failed to access ‘/home/tyler/.mongorc.js’: Permission denied
make: *** [install] Error 1
npm ERR! Linux 3.16.0-57-generic
npm ERR! argv "node" "/usr/bin/npm" "install" "-g" "mongo-hacker"
npm ERR! node v0.10.37
npm ERR! npm  v2.7.5
npm ERR! code ELIFECYCLE

npm ERR! mongo-hacker@0.0.11 install: `make install`
npm ERR! Exit status 2
```

It's the symbolic link that's failing to get permissions on my `~/.mongorc.js` file. Trying that command in isolation as myself works fine:

`ln -sf /usr/local/lib/node_modules/mongo-hacker/mongo_hacker.js ~/.mongorc.js`

And succeeds as root, too

`sudo ln -sf /usr/local/lib/node_modules/mongo-hacker/mongo_hacker.js ~/.mongorc.js`

Totally at a loss for why the `ln` fails within `sudo npm install` but not in isolation.

**Comment by Chirpizard** [comment]
I had same issue, but this worked for me also:
```
git clone --depth=1 https://github.com/TylerBrock/mongo-hacker.git
cd mongo-hacker
make install
```

Thanks for the suggestion.

**Comment by adrianosferreira** [comment]
After running a sudo chown $USER /usr/local/lib/node_modules the installation went fine.

**Comment by frederikreher** [comment]
@adrianosferreira solved my problem too.

**Comment by kaluks** [comment]
thanks @adrianosferreira , it worked for me.

**Comment by charlesfranciscodev** [comment]
same here thanks @adrianosferreira

**Comment by ZeFifi** [comment]
Hi guys !

```➜  ~ sudo chown $USER /usr/local/lib/node_modules
Password:
➜  ~ sudo npm install -g mongo-hacker

> mongo-hacker@0.0.15 install /usr/local/lib/node_modules/mongo-hacker
> make install

cat config.js base.js hacks/aggregation.js hacks/api.js hacks/auto_complete.js hacks/cmd_search.js hacks/color.js hacks/common.js hacks/count.js hacks/dbref.js hacks/find_and_modify.js hacks/helpers.js hacks/index_paranoia.js hacks/old_aggregation.js hacks/prompt.js hacks/ps.js hacks/randomise.js hacks/sh_status.js hacks/show.js hacks/uuid.js hacks/verbose.js > mongo_hacker.js
/bin/sh: mongo_hacker.js: Permission denied
make: *** [mongo_hacker.js] Error 1
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! mongo-hacker@0.0.15 install: `make install`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the mongo-hacker@0.0.15 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/me/.npm/_logs/2018-07-11T12_29_17_693Z-debug.log```

Still doesn't work for me :( Any idea ?
