### ISSUE TITLE
BinData subtype 3 output no longer works

### ISSUE THREAD

**Issue by jeffascentis** [TylerBrock/mongo-hacker#90]
// Insert UUID 3038afb2-6c99-4cf4-9f1e-5277c6a439ce

> db.testCollection.insert({ "_id" : BinData(3,"9EyZbLKvODDOOaTGd1Ienw==")})

Without mongo-hacker:

> db.testCollection.find()
> { "_id" : BinData(3,"9EyZbLKvODDOOaTGd1Ienw==") }

With mongo-hacker revision 3041d889a from May 8, 2013, the correct output is returned nicely:
{
  "_id": UUID("3038afb2-6c99-4cf4-9f1e-5277c6a439ce", "java")
}

With the current version 0.0.4, this is returned:
{
  "_id": UUID(undefined"default")
}

**Comment by stennie** [comment]
Closing old issues to clean up the backlog. This doesn't appear to be reproducible with the current version of Mongo Hacker.
